### ISSUE TITLE
Enabling BasicAuth causes liveness and readiness probes to fail.

### ISSUE THREAD

**Issue by dh-apporto** [runatlantis/helm-charts#106]
I tried to deploy 3.14.4 in my cluster today.  I changed the basicAuth username and password to something safer, but when the app was deployed, it failed the liveness and readiness probes with HTTP 401 errors.   When I set basicAuth to [], then the app was able to pass the liveness and readiness probes.

I ran into something similar on another app, and I had to encode the HTTP Authorization header as part of the probe definitions.   So, I think the helm chart should be updated to also encode basicAuth into the liveness/readiness probes.

**Comment by it-praktyk** [comment]
Hi!

I've observed the same issue recently.

I tried to resolve that - you can find a partial solution [here](https://github.com/it-praktyk/helm-charts/tree/Add_Basic_Auth_for_probes).

Furthermore, I stuck because I don't know how to store the secret as double-base64 encoded string. The value of the `Authorization` header has to be base64-encoded but when I check the value of the secret added by me, it's a plain text.

So, if someone knows how to enforce storing or assigning that header as the base64 encoded string, help will be welcomed.

**Comment by zerodayyy** [comment]
Affected by this issue as well. Steps to reproduce:

1. Use Atlantis chart `v3.14.6`
2. Set `basicAuth.username` and `basicAuth.password` Helm values
3. Deploy the chart to Kubernetes cluster
4. Observe `atlantis-0` Pod failing due to liveness and readiness probes failing on `atlantis` container with HTTP 401

As a temporary workaround without chart modifications, setting `livenessProbe.enabled` and `readinessProbe.enabled` to `false` allows the Pod to start receiving traffic.

There's an upstream issue about this in Atlantis itself: runatlantis/atlantis#1888

**Comment by it-praktyk** [comment]
It's probably fixed in the Atlantis itself [here](https://github.com/runatlantis/atlantis/commit/e06d181272ee22e62bbe37ed0a7035c2322bd364).

**Comment by NK74** [comment]
@it-praktyk Nice ;) 

Tested successfully on my side. The liveness probe now works with authentication enabled ✅
