### ISSUE TITLE
4.17.0 values.schema.json doesn't allow for fullnameOverride 

### ISSUE THREAD

**Issue by sharkymcdongles** [runatlantis/helm-charts#331]
When upgrading to 4.17.0, fullnameOverride is no longer allowed due to the new values.schema.json file:

```
✗ Helm upgrade failed: values don't meet the specifications of the schema(s) in the following chart(s):
atlantis:
- (root): Additional property fullnameOverride is not allowed
```

Either remove the value or allow it in the schema.

**Comment by cilindrox** [comment]
In addition to the above, I'm also running into an issue with the `global` prop not being allowed:

```
atlantis:
- (root): Additional property global is not allowed
```

This is triggered when including Atlantis as a subchart/dep.

**Comment by KeenanLawrence** [comment]
This value is still being used in the [_helpers.tpl](https://github.com/runatlantis/helm-charts/blob/atlantis-4.17.0/charts/atlantis/templates/_helpers.tpl#L15). Particularly important for our use case because we require a specific service name and this (or `nameOverride`) is the only way to set it.

**Comment by jamengual** [comment]
@roytev
