### ISSUE TITLE
Can't set replica count higher than 1

### ISSUE THREAD

**Issue by paymog** [runatlantis/helm-charts#412]
When I set the replica count higher than 1, I get the following error in a crash loop

```
Error: initializing server: starting BoltDB: timeout (a possible cause is another Atlantis instance already running)
```

**Comment by GMartinez-Sisti** [comment]
Hi @paymog, to increase replicas you need to have a shared database. Atlantis allows using redis instead of boltdb for this, but it will not set it up for you. Please take a look here:

https://github.com/runatlantis/helm-charts/blob/848e08346c48182605ccaaa37e51af4b784703d4/charts/atlantis/values.yaml#L705-L719

**Comment by paymog** [comment]
aaah gotcha. It would be nice if that was documented for the `replicaCount` value in the helm chart

**Comment by GMartinez-Sisti** [comment]
> aaah gotcha. It would be nice if that was documented for the `replicaCount` value in the helm chart

Maybe we can do a check and fail when `replica > 1`  && `lockingDbType != redis`. Feel free to send a PR 😃

**Comment by paymog** [comment]
That would be great, I think just one line of doc would also be useful 🙂
